version: '3'
services:
    nginx:
        build: .
        image: "chatroom-nginx"
        networks:
            - chatroom
        ports:
            - 80:80
    frontend:
        build: ./react-frontend
        image: "chatroom-frontend"
        networks:
            - chatroom
    backend:
        build: ./express-backend
        image: "chatroom-backend"
        networks:
            - chatroom
networks:
    chatroom:
